#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

service-create-database-cmd() {
  #E create a $PLUGIN_COMMAND_PREFIX database named tasty for service named lolipop
  #E dokku $PLUGIN_COMMAND_PREFIX:create-database lolipop tasty
  declare desc="create a $PLUGIN_SERVICE database for specified service"
  local cmd="$PLUGIN_COMMAND_PREFIX:create-database" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1" DATABASE="$2" CREATE_FLAGS_LIST="${@:3}"

  service_create_database "$SERVICE" "$DATABASE" "${@:3}"
}

service-create-database-cmd "$@"
